name: NativeDimensions
main: jasonwynn10\NativeDimensions\Main
src-namespace-prefix: jasonwynn10\NativeDimensions
version: 0.1.0
api: 4.0.0
description: "A plugin which loads dimensions within worlds and provides an API for managing dimensions across worlds"
author: "jasonwynn10"
load: STARTUP
softdepend:
- MultiWorld
protocol: [407]