name: NativeDimensions
main: jasonwynn10\NativeDimensions\Main
src-namespace-prefix: jasonwynn10\NativeDimensions
version: 1.0.0-beta8
api: 5.0.0-ALPHA1
description: "A plugin which loads dimensions within worlds and provides an API for managing dimensions across worlds"
author: "jasonwynn10"
load: STARTUP